### ISSUE TITLE
Official release

### ISSUE THREAD

**Issue by DarioSarra** [JuliaStats/Survival.jl#19]
Would it be possible to officially release this package? So far I clone it for usage but I often encounter issues with it. Last time I was generating a new package using PckTemplates and I got an error due to Survival.

Activating environment at `~/.julia/environments/v1.3/Project.toml`
[ Info: Committed 6 files/directories: src/, Project.toml, test/, README.md, LICENSE, .gitignore
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Survival [8a913413]:
 Survival [8a913413] log:
 ├─Survival [8a913413] has no known versions!
 └─restricted to versions * by FlippingModel [d1f21f3f] — no versions left
   └─FlippingModel [d1f21f3f] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─FlippingModel [d1f21f3f] is fixed to version 0.1.0

**Comment by ararslan** [comment]
@JuliaRegistrator register

**Comment by ararslan** [comment]
@JuliaRegistrator register

**Comment by ararslan** [comment]
The package is now registered.
