### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by ya0** [JuliaStats/Survival.jl#51]
Hello, could you release a new version so the "new" structure is downloadable. I have a workflow using the survival package i would like to share but i would like to tell the people to use `] add Survival` instead of `] add https://github.com/JuliaStats/Survival.jl.git`.

Thank you.

More specifially: a few years ago you changed the api and functionality on stable but the released version is 2 years old.

**Comment by ararslan** [comment]
Version 0.3.0 will be available once https://github.com/JuliaRegistries/General/pull/86456 has been merged. Thanks!
