### ISSUE TITLE
EventTables does not exist

### ISSUE THREAD

**Issue by casasgomezuribarri** [JuliaStats/Survival.jl#52]
I'm really happy to have come across this package! Very handy and simple.

I am trying to compute Kaplan-Meier estimates to make a survival curve. I understand from the docs that I need an `EventTable` to pass to the `KaplanMeier` function, however, when I do `EventTable(eventtimes)` I get an error. I checked and it seems that the type `EventTable` doesn't exist:

```
using Survival;
? Survival.EventTable
```
>   No documentation found.
> 
>   Binding Survival.EventTable does not exist.

To control my environment is alright:

```
? Survival.EventTime
```
> EventTime{T}
> 
>   Immutable object containing the real-valued time to an event as well as an indicator of whether the time corresponds to an observed event (true) or right censoring (false).

Am I doing something wrong? I am using Survival v0.2.2 on Julia 1.8.2

**Comment by ya0** [comment]
EventTable is not in the package 0.2.2 i had the same problem when starting to use this module. The documentation is set to latest wich is not 0.2.2 but the current code on github which includes event tables...
I have already asked for a version bump #51

**Comment by ya0** [comment]
Thank you @ararslan for the release. I am looking forward to the future of this package!

**Comment by casasgomezuribarri** [comment]
Thank you @ararslan for the quick release! Gotta love Julia...
